from time import sleep
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select

opt = webdriver.ChromeOptions()
opt.add_experimental_option('detach', True)

driver = webdriver.Chrome(options=opt)

driver.maximize_window()

driver.get("https://www.facebook.com/")

driver.find_element(By.XPATH, "//a[@class='_42ft _4jy0 _6lti _4jy6 _4jy2 selected _51sy']").click()
sleep(1)
a = driver.find_element(By.XPATH, "//input[@aria-label='First name']")
a.click()
sleep(0.5)
a.send_keys("shreyash")
sleep(0.5)
b = driver.find_element(By.XPATH, "//input[@name='lastname']")
b.click()
sleep(0.5)
b.send_keys("B")
sleep(0.5)
c = driver.find_element(By.XPATH, '//select[@aria-label="Day"]')
A = Select(c)
A.select_by_index(0)
sleep(0.5)
d = driver.find_element(By.XPATH, '//select[@aria-label="Month"]')
B = Select(d)
B.select_by_index(11)
sleep(0.5)
e = driver.find_element(By.XPATH, '//select[@aria-label="Year"]')
C = Select(e)
C.select_by_visible_text('1999')
sleep(0.5)
f = driver.find_element(By.XPATH, '//input[@value="2"]')
f.click()
g = driver.find_element(By.XPATH, '//input[@name="reg_email__"]')
g.click()
sleep(0.5)
g.send_keys('shreyashb11@gmail.com')
sleep(0.5)
h = driver.find_element(By.XPATH, '//input[@data-type="password"]')
h.click()
sleep(0.5)
h.send_keys("tomorrow_is_now")
sleep(0.5)
i = driver.find_element(By.XPATH, '//button[@name="websubmit"]')
sleep(0.5)
i.click()
sleep(5)
# driver.close()